### ISSUE TITLE
Did not work for react-router-dom v 6.10.0

### ISSUE THREAD

**Issue by sayjin93** [Bilal-Bangash/detecting-route-change-react-route-dom-v6#10]
Please can you update the code to make it works for latest version of react-router-dom and react ?

**Comment by Swanand-Wagh** [comment]
Yes please

**Comment by swalker326** [comment]
What error are you getting? Do you have a minimal reproducible example in a code sandbox or stack blitz?

**Comment by swalker326** [comment]
Also, for anyone else here: https://github.com/remix-run/react-router/issues/8139#issuecomment-1396078490

Looks like this is functionality that is built into newer versions of react-router.
